# Generated by database migrator
import peewee
import datetime


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "users",
        require_password_change=peewee.BooleanField(default=False),
        password_expires=peewee.DateTimeField(null=True, default=None),
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("users", ["require_password_change", "password_expires"])
