# Generated by database migrator
import peewee


def _column_exists(database, table_name, column_name):
    cursor = database.execute_sql(f"PRAGMA table_info({table_name})")
    rows = cursor.fetchall()
    return any(row[1] == column_name for row in rows)


def migrate(migrator, database, **kwargs):
    # NOTE:
    # MigrationManager runs migrator.run() *after* this function returns,
    # so any SQL in this function cannot rely on queued add_columns calls.
    # Add the column immediately with raw SQL, then perform backfill updates.
    if not _column_exists(database, "servers", "monitoring_type"):
        database.execute_sql(
            "ALTER TABLE servers ADD COLUMN monitoring_type VARCHAR(255) "
            "DEFAULT 'minecraft-java'"
        )

    database.execute_sql(
        """
        UPDATE servers
        SET monitoring_type = CASE
            WHEN type IN ('minecraft-java', 'minecraft_bedrock', 'minecraft_java') THEN 'minecraft-java'
            WHEN type IN ('minecraft-bedrock', 'minecraft_bedrock') THEN 'minecraft-bedrock'
            WHEN type = 'hytale' THEN 'hytale'
            WHEN type = 'steam_cmd' THEN 'steam_cmd'
            ELSE COALESCE(monitoring_type, 'minecraft-java')
        END
        """
    )
    database.execute_sql(
        """
        UPDATE servers
        SET type = 'lobby'
        WHERE type IN ('minecraft-java', 'minecraft-bedrock', 'hytale', 'steam_cmd')
        """
    )


def rollback(migrator, database, **kwargs):
    if _column_exists(database, "servers", "monitoring_type"):
        migrator.drop_columns("servers", ["monitoring_type"])
