# Generated by database migrator
import peewee


LEGACY_MONITORING_TYPES = (
    "minecraft-java",
    "minecraft-bedrock",
    "hytale",
    "steam_cmd",
)


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "servers", monitoring_type=peewee.CharField(default="minecraft-java")
    )
    database.execute_sql(
        """
        UPDATE servers
        SET monitoring_type = CASE
            WHEN type IN ('minecraft-java', 'minecraft_bedrock', 'minecraft_java') THEN 'minecraft-java'
            WHEN type IN ('minecraft-bedrock', 'minecraft_bedrock') THEN 'minecraft-bedrock'
            WHEN type = 'hytale' THEN 'hytale'
            WHEN type = 'steam_cmd' THEN 'steam_cmd'
            ELSE 'minecraft-java'
        END
        """
    )
    database.execute_sql(
        """
        UPDATE servers
        SET type = 'lobby'
        WHERE type IN ('minecraft-java', 'minecraft-bedrock', 'hytale', 'steam_cmd')
        """
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns("servers", ["monitoring_type"])
